### ISSUE TITLE
Grouped version updates from Dependabot

### ISSUE THREAD

**Issue by rollingmoai** [github/combine-prs#24]
Not an issue, but the new grouped version updates feature from Dependabot already resolves the main use case mentioned in the readme for this action: https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
```yml
version: 2
  updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: weekly
    # New!
    groups:
      # This is the name of your group, it will be used in PR titles and branch names
      dev-dependencies:
        # A pattern can be...
        patterns:
          - "rubocop" # a single dependency name
          - "aws*"  # or a wildcard string that matches multiple dependencies
          # If you'd simply like to group as many dependencies together as possible, 
          # you can use the wildcard * - but keep in mind this may open a very large PR!
        # Additionally, you can specify any dependencies to be excluded from the group
        exclude-patterns:
          - "aws-sdk"
```

Maybe this should be mentioned in the readme?
